image: docker:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  image: node:12-alpine
  script:
    - npm install
    - npm test
  rules:
    if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  environment:
    name: $_ENV
  script:
    - echo "Deplyoing to $CI_ENVIRONMENT_NAME"
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json 
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml --substitutions=_ENVIRONMENT=$CI_ENVIRONMENT_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        _ENV: staging
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        _ENV: production
    - when: never