# File: cloudbuild.yaml
steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/relic-finder-test/cms/strapi:production', '.' ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/relic-finder-test/cms/strapi:production']
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'strapi', '--image', 'gcr.io/$PROJECT_ID/relic-finder-test/cms/strapi:production', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
